### PR TITLE
bee-p to master

### PR DESCRIPTION
**Pull request by kwek20**
Whoeps i forgot the client change, only did core in last pr

### CODE REVIEW

**Comment by nothingismagick** [comment]
Didn't @thibault-martinez say something about NOT using anything from the bee prototype?

**Comment by kwek20** [comment]
Probably fine for the legacy branch

**Comment by thibault-martinez** [comment]
Why are we spending time on `iota-1.0` though ?
`bee-p/master` hasn't received any update in a long time and won't receive anymore at all.

**Comment by kwek20** [comment]
streams still uses iota-1.0, as i assume all other projects for pre-chrysalis2.0 :=) @thibault-martinez 
No time was needed to be spend tho, its jsut since the default branch changed, we need to specify.

Ill update it to the exact commit instead, so its always good to go

**Comment by thibault-martinez** [comment]
Yeah sure, I am just saying that `bee-p/master` never reached and will never reach maturity. I am not exactly sure what you expect from it, I just want to warn that we won't provide support or invest time in it anymore :)

**Comment by lucasfernog** [comment]
We also won't invest time on iota-1.0 anymore but if this is just to fix some issue on streams until they migrate to chrysalis, that's fine. I'll merge this.

**Comment by kwek20** [comment]
Yea was jsut a warning saying 2 imports using different branches, all good! Thanks @lucasfernog

**Pull request merged**
