### PR TITLE
Fixes typo in the exports of the WASM web bindings

### PR DESCRIPTION
**Pull request by kuhlmannmarkus**

### CODE REVIEW

**Comment by nothingismagick** [comment]
not sure i agree with this semantically, because camelCase is used to demarcate different words. In my book `broadcast` is always one word and i would never intuit that it should be written `broadCast`. nevertheless, this should be the same everywhere so your concern is definitely valid.

**Comment by kuhlmannmarkus** [comment]
I think you are right @nothingismagick

**Comment by wusyong** [comment]
Well... `broadcast` is a word in my understanding too. Besides, I followed the naming rule in [iota.js](https://github.com/iotaledger/iota.js/#api-reference).

**Comment by wusyong** [comment]
@kuhlmannmarkus thanks for the PR. I think it's the function name has typo instead of export. But I think it's good to merge as a hot fix.

**Pull request merged**
