### PR TITLE
infra: Add rustfmt configuration

### PR DESCRIPTION
**Pull request by wusyong**

### CODE REVIEW

**Comment by njaremko** [comment]
Why are you messing with rustfmt defaults?

**Comment by wusyong** [comment]
Hey @njaremko, sorry I don't know you are still maintaining. I'm just assigned recently and going to cleanup a bit. Mostly to support the incoming `bee` project. This `rustfmt.toml` is proposed by the bee team.

Ideally, this is also going to be the basic library for other projects written in Rust in the future.

**Comment by njaremko** [comment]
The style of this project isn't really applicable to any projects using it. I'm against straying from defaults for rustfmt. Similar to other formatters, most projects are intended to follow the "one true format" to facilitate readability between projects.

**Comment by wusyong** [comment]
I see. I will inform this to others and might consider close it later.

Update: After some discussion, we decided to go for minimal rustfmt which is `edition = "2018"` only for now. This should be more appropriate and literally nothing has changed.

**Comment by njaremko** [comment]
@oopsmonk why have you asked me to review these changes? It appears this PR is empty now

**Comment by oopsmonk** [comment]
> @oopsmonk why have you asked me to review these changes? It appears this PR is empty now

ho.. we agree only to keep `edition` in the rustfmt.toml. :P

**Comment by njaremko** [comment]
@wusyong Nothing changed because rustfmt looks at edition in cargo.toml, so you've created a rustfmt file for no reason

**Comment by wusyong** [comment]
Looks like [it is](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#edition). The original purpose of this PR is adding custom formatting rules. But at this stage it seems we don't need it anymore. I still feel like config like `wrap_comments` can be useful. If you insist, I can remove the file in future pull request.

**Comment by njaremko** [comment]
I mean, people shouldn't be making crazy long single line comments unless there's a reason for it (is the reasoning behind wrap_comments defaulting to false)

**Comment by wusyong** [comment]
That's reasonable, I will open revert PR tomorrow.

**Pull request merged**
