### PR TITLE
chore: update license to Apache 2.0

### PR DESCRIPTION
**Pull request by cvarley100**
# Description
IOTA Foundation projects are licensed under [Apache License v2.0](https://www.apache.org/licenses/LICENSE-2.0). The license for iota.rs needs to change from MIT to Apache 2.0. 

To do so, we need approval from all external contributors that have committed code to the repository. 

External contributors:

- [x] @njaremko 
- [x] @Thoralf-M
- [x] @jkuruvilla 
- [x] @mayjs 
- [x] @kuhlmannmarkus 
- [x] @huhn511 

If you're happy with the license change, please reply with the following:
```
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.
```
If you're not happy with the license change, please reply with details. Thanks!

### CODE REVIEW

**Comment by miklogg** [comment]
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Comment by njaremko** [comment]
​I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Comment by Thoralf-M** [comment]
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Comment by mayjs** [comment]
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Comment by kuhlmannmarkus** [comment]
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Comment by huhn511** [comment]
I hereby agree to license my existing contributions to the iota.rs project under the terms of the Apache License v2.0.

**Review by wusyong — APPROVED** [review]

**Pull request merged**
