### PR TITLE
bindings/nodejs: fix minPoWScore assertion on devnet

### PR DESCRIPTION
**Pull request by jyhi**
This PR fixes an obsolete assertion on the devnet about the minimum PoW score.

See also #782.

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Comment by jyhi** [comment]
There turns out to be more problems... can't merge yet.

**Comment by jyhi** [comment]
@Thoralf-M I'm not sure how to change the tests to let them pass.

**Comment by Thoralf-M** [comment]
@lmy441900 I requested more funds from the faucet to the addresses and changed the addresses to one with a higher index, so the transactions will now move funds to the next address (sending to their own address is currently not possible if the remainder would also go to it, this will change with stardust)

**Comment by Thoralf-M** [comment]
But since we run them in parallel we get conflicting transactions, maybe better to disable the transaction tests

**Comment by jyhi** [comment]
@Thoralf-M I have no idea about the failures on Node.js 16 on Windows.

**Comment by Thoralf-M** [comment]
@lmy441900 seems like we need to install Python https://github.com/neon-bindings/neon/issues/844

**Comment by Thoralf-M** [comment]
Btw `Examine the WebAssembly Bindings / Test` fails with a neon error, do these lines need to be changed to `bindings/wasm`?
https://github.com/iotaledger/iota.rs/blob/b25d6687e6fedd38ee44f7c99f448a2b1f4ca9bb/.github/workflows/examine-wasm-bindings.yml#L68
https://github.com/iotaledger/iota.rs/blob/b25d6687e6fedd38ee44f7c99f448a2b1f4ca9bb/.github/workflows/examine-wasm-bindings.yml#L78

Also I'm just seeing we install clang/LLVM, but I think we only need that for the node.js binding and not for wasm

**Pull request merged**
