### PR TITLE
Fix python package

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Fix python package

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

`pip install . && python3 examples/00_get_info.py`

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by thibault-martinez — COMMENTED** [review]
There should be only one lock at the root for everything, `client/bindings/python/Cargo.lock` shouldn't be needed

**Comment by Thoralf-M** [comment]
:+1: was just a leftover from testing

**Review by thibault-martinez — APPROVED** [review]

**Comment by Dr-Electron** [comment]
This isn't working on my MacBook. So I tried it with a clean setup.

1. Open https://gitpod.io/#https://github.com/iotaledger/iota.rs/pull/1629
2. Run:
    1. `sudo apt update`
    2. `sudo apt install libudev-dev -y`
    3. `cd client/bindings/python/`
    4. `pip install -r requirements-dev.txt`
    5. `pip install .`
    6. `python`
3. Try to import `from iota_client import IotaClient`

I get:
```
>>> from iota_client import IotaClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/iota.rs/client/bindings/python/iota_client/__init__.py", line 1, in <module>
    from .iota_client import *
ModuleNotFoundError: No module named 'iota_client.iota_client'
```

Same on macOS

**Comment by Dr-Electron** [comment]
Nevermind, everything works if you execute `python` in another folder 😅

**Review by Dr-Electron — APPROVED** [review]

**Review by kwek20 — APPROVED** [review]

**Pull request merged**
