### PR TITLE
Support native TLS certs

### PR DESCRIPTION
**Pull request by rajivshah3**
- feature: Expose native TLS certs via features
- Use wss for secure WebSocket and load native certificates

See iotaledger/iota-sdk#56, iotaledger/firefly#2111

### CODE REVIEW

**Comment by rajivshah3** [comment]
I had a bit of trouble with the features, so I'm not sure what the best way to do those is 🤔

**Comment by thibault-martinez** [comment]
What's the status on that @rajivshah3 ?

**Comment by rajivshah3** [comment]
@thibault-martinez I haven't had time to work on this in a while unfortunately. When I have some more time I can update this PR and test it

**Comment by thibault-martinez** [comment]
Hi @rajivshah3, it seems this probably won't be done before Shimmer hits the IOTA mainnet so we're going to close this PR and open an issue for Shimmer instead. Please re-open if you really you to have this on mainnet.

**Pull request closed without merging**
