### PR TITLE
Add getEssenceHash()

### LINKED ISSUE #920: add getTransactionUnsiged method
For some people this method will be very helpful!
`/// get transaction unsigned`
`#[wasm_bindgen(js_name = getTransactionUnsigned)]`
`  pub fn get_transaction_unsigned(`
`    &self,`
`   prepared_transaction_data: JsValue,`
` ) -> Result<Promise, String> {`
` let client = self.client.clone();`
`  let promise: Promise = future_to_promise(async move {`
`    client.client .message().get_transaction_unsigned(`
`            prepared_transaction_data.into_serde().map_err(wasm_error)?`
`          ).await.map_err(wasm_error)`
`    });`
`    Ok(promise)`
` }`

`/// get transaction unsigned`
`    pub async fn get_transaction_unsigned(`
`        &self,`
`        prepared_transaction_data: PreparedTransactionData`
`    ) -> Result<String> {`
`        let essence = prepared_transaction_data.essence;`
`        let hashed_essence = essence.hash();`
`        let essence_hex_str = hex::encode(hashed_essence);`
`        Ok(essence_hex_str)`
`    }`

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Add getEssenceHash()

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota.rs/issues/920

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

With added test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Thoralf-M** [comment]
@cao148 would you be happy with this?

**Comment by cao148** [comment]
@Thoralf-M Yean! It's so cool.

**Comment by cao148** [comment]
@Thoralf-M My expectation is that the method getEssenceHash() can be called via npm i @iota/client.

**Review by thibault-martinez — APPROVED** [review]

**Comment by Thoralf-M** [comment]
@cao148 but this is wasm code and that will be available via `@iota/client-wasm`

**Pull request merged**
