### PR TITLE
examples: fix unnecessary use of `to_vec`

### PR DESCRIPTION
**Pull request by jyhi**
Fix of clippy::unnecessary_to_owned provided by clippy 0.1.60 (777bb86 2022-01-20).

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Comment by jyhi** [comment]
How come I cannot get those warnings in CI locally :\

**Comment by jyhi** [comment]
So `clippy::ptr-arg` and `clippy::needless-question-mark` look like two newly-added lints.

**Comment by jyhi** [comment]
@Thoralf-M ac66167 applies a new Clippy lint changing `&Vec` to `&[]` (https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg). I presume there won't be any API break (`Vec`s just get `Deref`fed). What do you think?

**Comment by Thoralf-M** [comment]
Yes should be fine

**Pull request merged**
